import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { dbConnect } from "@/services/mongos";
import AuthProvider from "./providers/AuthProvider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eventry ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  await dbConnect();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main className="py-8">
            {children}
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
